### ISSUE TITLE
怎么添加多台路由器

### ISSUE THREAD

**Issue by 2696791698** [thun888/mirouter-ui#21]
我第二台路由器的ip是192.168.31.157, 那么我的配置文件该怎么写

**Comment by thun888** [comment]
``` yaml
# 路由器设备配置
dev:
  - password: ""  # 路由器密码
    key: "a2ffa5c9be07488bbb04a3a47d3c5f6a"  # 路由器密钥
    ip: "192.168.31.1"  # 路由器IP地址
    islocal: false  # 是否为本地模式
  - password: ""  # 路由器密码
    key: "a2ffa5c9be07488bbb04a3a47d3c5f6a"  # 路由器密钥
    ip: "192.168.31.157"  # 路由器IP地址
    islocal: false  # 是否为本地模式

# 历史记录配置
history:
  enable: true  # 是否启用历史记录
  maxsaved: 3000  # 最大保存记录数
  sampletime: 300  # 采样时间（秒）

# 应用配置
debug: true  # 调试模式
port: 6789  # 服务端口
address: "0.0.0.0"  # 监听地址
tiny: false  # 精简模式
flushTokenTime: 1800  # Token刷新时间（秒）
safemode: true  # 安全模式 
api_key: ""  # 认证令牌
```
